### ISSUE TITLE
customizing the Highcharts theme

### ISSUE THREAD

**Issue by amorphous1** [kirjs/react-highcharts#5]
I'd like to be able to change the Highcharts theme. I patched the source to add the below at the start of renderChart:

    if (this.props.theme) {
      Highcharts.theme = this.props.theme;
      Highcharts.setOptions(Highcharts.theme);
    }

This works fine when used like so:

    <Highcharts config = {highchartsConfig} theme = {HighchartsTheme.dark}></Highcharts>

Is there a simpler/better way to customize the theme? If not, could you add the code above?

**Comment by kirjs** [comment]
Hi amorphous1, thanks for the suggestion. 

I'm not a big fan of passing theme as an instance property, because it sets global value, and would affect other instances. 

I exposed the actual Highcharts object as a property, so you should be able to access it like this: 
```
Highcharts.Highcharts.setOptions(HighchartsTheme.dark);
```

I'll think about a better naming scheme, but that should solve the issue for now. 
Let me know if this works for you.

**Comment by amorphous1** [comment]
Thanks for the quick update! I can see the point about not wanting to change global state via an instance parameter. Your solution works fine for me.

**Comment by elisechant** [comment]
if you want to store Theme you need to set that on the Highcharts Primitive. This library doesn't solve this use case, but you could use react-highcharts-wrapper instead which does - https://www.npmjs.com/package/react-highcharts-wrapper
